### ISSUE TITLE
imagemagick@6であることをreadmeに明記したほうが良さそう

### ISSUE THREAD

**Issue by bino98** [speee/iiopt#12]
## 概要
`brew install imagemagick` だと、 7がインストールされるが、iioptで使用しているバージョンは6だったので、少し辛かった。

## 今回発生した内容
iioptでjpegをオプティマイズしようとしたところ、モジュールが見つからない旨のエラーが発生した。

```sh
Command failed: identify -format "%Q" ./gohugo-default-sample-hero-image.jpg
identify: unable to load module `/usr/local/Cellar/imagemagick@6/6.9.8-10/lib/ImageMagick//modules-Q16/coders/jpeg.la': file not found @ error/module.c/OpenModule/1290.
identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/504.
```

そのため、imagemagickのバイナリをインストールせず、手元でコンパイルしてインストールすることにした。

```sh
brew remove imagemagick && brew install --build-from-source imagemagick
```

しかし、同じエラーがでる。よく観たら、私が再インストールしたimagemagickはバージョンが7だが、iioptではバージョン6を使用していたため、少し辛かった。

```sh
brew remove imagemagic@6 && brew install  --build-from-source imagemagic@6 && brew link --force imagemagick@6
```

⇡こちらで解決。
エラー文を良く見ろよということだと思いつつ、readmeにimagemagic6である旨がかいてあるとちょっと親切だなと思ったためIssue化

## 参考にした記事
https://qiita.com/chanibarin/items/a6aee2a47cbba9f0ab09
https://github.com/Homebrew/legacy-homebrew/issues/14325

**Comment by selmertsx** [comment]
issueの起票ありがとうございます！！
imagemagickのバージョン、6でも7でも動くようにしたいっすなぁ...

**Comment by selmertsx** [comment]
```
$ magick --version
Version: ImageMagick 7.0.8-8 Q16 x86_64 2018-07-23 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
$ npx ts-node bin/cli images/sample.jpg --out-dir ./images

    path: images/sample.jpg
    before file size: 100060
    after file size: 65043
```

**Comment by selmertsx** [comment]
現状のコードで確認したところ、imagemagick 7で問題なく動作しました。
なので、もしかしたら違う原因があると思います

**Comment by selmertsx** [comment]
違うことが原因そうなので、一旦 closeしておきますね。
どうしても上手く行かなければ、またissueをopenしてください〜

**Comment by bino98** [comment]
are!なんと!
そうなんですね、これは大変失礼しました...。
調査も頂き恐縮です。。ありがとうございました
